version: '3.9'

services:
  swarm1:
    container_name: swarm1
    image: docker1
    restart: always
    network_mode: host
    volumes:
      - ./root:/root:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
  swarm2:
    container_name: swarm2
    image: docker1
    restart: always
    network_mode: host
    volumes:
      - ./root:/root:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z


  swarm3:
    container_name: swarm3
    image: docker1
    restart: always
    network_mode: host
    volumes:
      - ./root:/root:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z