version: '3.9'

services:
  swarm1:
    container_name: swarm1
    image: docker1
    restart: always
    networks:
      - swarm
    volumes:
      - ./root:/root:rw,z
  swarm2:
    container_name: swarm2
    image: docker1
    restart: always
    networks:
      - swarm
    volumes:
      - ./root:/root:rw,z

  swarm3:
    container_name: swarm3
    image: docker1
    restart: always
    networks:
      - swarm
    volumes:
      - ./root:/root:rw,z

networks:
  swarm:
    name: swarm
    driver: host